# Generated by Django 5.2.18 on 2026-10-08 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_no",
                    models.CharField(
                        help_text="The store code. Temporary codes end in -A, -B and so on until confirmed.",
                        max_length=40,
                        unique=True,
                        verbose_name="Part No.",
                    ),
                ),
                (
                    "original_part_no",
                    models.CharField(
                        blank=True,
                        help_text="The code exactly as it appeared in the last import.",
                        max_length=40,
                        verbose_name="Part No. in spreadsheet",
                    ),
                ),
                (
                    "import_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Internal: links this item to its spreadsheet row on re-import.",
                        max_length=60,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("import", "Imported"), ("manual", "Added by admin")],
                        default="manual",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "catalogue_name",
                    models.CharField(
                        blank=True,
                        help_text="Name from the catalogue spreadsheet. Updated on each import.",
                        max_length=300,
                        verbose_name="Original name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="The name users see. Never changed by an import.",
                        max_length=300,
                    ),
                ),
                (
                    "trade_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Trade price (£) per unit. For packs, the price of one pack. For area items, the price per m².",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "measure_type",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("pack", "Pack"),
                            ("area", "Area (m²)"),
                            ("linear", "Linear (m)"),
                            ("cut", "Cut to order (m)"),
                            ("whole", "Whole items only"),
                        ],
                        default="each",
                        max_length=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="each",
                        help_text='Shown to users next to the quantity, e.g. "each", "pack", "m²", "m", "roll".',
                        max_length=40,
                        verbose_name="Unit of measure",
                    ),
                ),
                (
                    "pack_size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many are in one pack (1 if not sold in packs).",
                    ),
                ),
                (
                    "catalogue_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cut-to-order items only: the length the trade price covers (e.g. 3.0 for worktops).",
                        max_digits=6,
                        null=True,
                        verbose_name="Catalogue length (m)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_flammable",
                    models.BooleanField(default=False, verbose_name="Flammable"),
                ),
                (
                    "is_incomplete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Missing a name or trade price. Not orderable until completed.",
                        verbose_name="Incomplete",
                    ),
                ),
                (
                    "code_to_confirm",
                    models.BooleanField(
                        default=False,
                        help_text="Temporary code given on import (duplicate or placeholder). Clears when the Part No. is changed.",
                        verbose_name="Code to be confirmed",
                    ),
                ),
                (
                    "name_check",
                    models.BooleanField(
                        default=False,
                        help_text="The imported name still looks garbled after automatic repair.",
                        verbose_name="Check name",
                    ),
                ),
                (
                    "deactivated_by_import",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["section__sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "key",
                    models.SlugField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Waiting to be applied"),
                            ("applied", "Applied"),
                            ("discarded", "Discarded"),
                        ],
                        default="preview",
                        max_length=10,
                    ),
                ),
                ("rows", models.JSONField(default=list)),
                ("report", models.JSONField(default=dict)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkedItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("reminder_text", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="linked_groups", to="catalogue.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="catalogue.section",
            ),
        ),
    ]
