# Generated by Django 5.2.18 on 2026-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="roll_width_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vinyl and other roll goods cut to length: the roll width. Cut length × roll width × price per m² gives the line value.",
                max_digits=5,
                null=True,
                verbose_name="Roll width (m)",
            ),
        ),
    ]
