# Generated by Django 5.2.18 on 2026-10-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_item_roll_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="roll_width_m",
        ),
    ]
