# Generated by Django 5.2.18 on 2026-10-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_remove_item_roll_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Default quantity (packs for pack items). Measured items: the user enters measurements.",
                    ),
                ),
                (
                    "prompts_kit",
                    models.BooleanField(
                        default=False,
                        help_text="Adding this item to an order offers the rest of the kit.",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_memberships",
                        to="catalogue.item",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_items",
                        to="catalogue.kit",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="LinkedItemRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text='Optional reason shown to the user, e.g. "Sealant needs an applicator gun".',
                        max_length=200,
                    ),
                ),
                (
                    "two_way",
                    models.BooleanField(
                        default=False,
                        help_text="Also suggest the trigger item when a suggested item is added.",
                        verbose_name="Suggest both ways",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_items",
                    models.ManyToManyField(
                        help_text="…suggest these items.",
                        related_name="+",
                        to="catalogue.item",
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        help_text="When this item is added to an order…",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_rules",
                        to="catalogue.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "linked item rule",
                "ordering": ["trigger__part_no"],
            },
        ),
        migrations.DeleteModel(
            name="LinkedItemGroup",
        ),
        migrations.AddConstraint(
            model_name="kititem",
            constraint=models.UniqueConstraint(
                fields=("kit", "item"), name="kit_item_once"
            ),
        ),
    ]
