# Generated by Django 5.2.18 on 2026-10-08 18:33

import django.db.models.deletion
from django.db import migrations, models


def mark_flammable(apps, schema_editor):
    apps.get_model("catalogue", "Section").objects.filter(key="flammable").update(is_flammable=True)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_linked_items_and_kits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="section",
            name="is_flammable",
            field=models.BooleanField(
                default=False,
                help_text="Items in this section are flagged FLAMMABLE on orders and in the stores email.",
                verbose_name="Flammable store",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Blank = Unsectioned (its section was removed).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalogue.section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="key",
            field=models.SlugField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Lower numbers are shown first.",
                verbose_name="Order",
            ),
        ),
        migrations.RunPython(mark_flammable, migrations.RunPython.noop),
    ]
