# Generated by Django 5.2.18 on 2026-10-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_editable_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="import_section",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Internal: the section of the file this item was last imported from. A re-import of that file can deactivate the item if it is no longer listed, wherever the item now sits.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="section_locked",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Section set by an admin: re-imports leave the section alone.",
            ),
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Order"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="catalogue.section",
                    ),
                ),
            ],
            options={
                "ordering": ["section__sort_order", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="subsection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalogue.subsection",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsection",
            constraint=models.UniqueConstraint(
                fields=("section", "name"), name="subsection_name_once"
            ),
        ),
    ]
