# Generated by Django 5.2.18 on 2026-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetentionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("scheduled", "Daily job"), ("manual", "Run by hand")],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "run_by",
                    models.CharField(
                        blank=True,
                        help_text="Admin who pressed Run now, if any.",
                        max_length=150,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "cutoff_delivery_date",
                    models.DateField(
                        help_text="Orders delivered on or before this date were anonymised."
                    ),
                ),
                ("orders_anonymised", models.PositiveIntegerField(default=0)),
                (
                    "order_numbers",
                    models.JSONField(
                        default=list, help_text="Order numbers anonymised in this run."
                    ),
                ),
                ("drafts_deleted", models.PositiveIntegerField(default=0)),
                ("succeeded", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
