# Generated by Django 5.2.18 on 2026-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retention", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retentionrun",
            old_name="orders_anonymised",
            new_name="orders_deleted",
        ),
        migrations.AlterField(
            model_name="retentionrun",
            name="cutoff_delivery_date",
            field=models.DateField(
                help_text="Orders delivered on or before this date were deleted."
            ),
        ),
        migrations.AlterField(
            model_name="retentionrun",
            name="order_numbers",
            field=models.JSONField(
                default=list, help_text="Order numbers deleted in this run."
            ),
        ),
    ]
