# Generated by Django 5.2.18 on 2026-10-08 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0003_item_roll_width"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumberCounter",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("requester_name", models.CharField(blank=True, max_length=150)),
                ("job_number", models.CharField(blank=True, max_length=30)),
                ("property_address", models.TextField(blank=True)),
                (
                    "job_number_key",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("anonymous_id", models.CharField(blank=True, max_length=20)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("void", "Void"), ("occupied", "Occupied")],
                        max_length=10,
                    ),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="The order date.", null=True
                    ),
                ),
                ("amended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amendment_pending",
                    models.BooleanField(
                        default=False,
                        help_text="Changed since stores were last sent the order.",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anonymised_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_non_stocked", models.BooleanField(default=False)),
                ("part_no", models.CharField(blank=True, max_length=40)),
                ("name", models.CharField(max_length=300)),
                ("section_name", models.CharField(blank=True, max_length=60)),
                (
                    "measure_type",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("pack", "Pack"),
                            ("area", "Area (m²)"),
                            ("linear", "Linear (m)"),
                            ("cut", "Cut to order (m)"),
                            ("whole", "Whole items only"),
                        ],
                        default="each",
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(default="each", max_length=40)),
                ("pack_size", models.PositiveIntegerField(default=1)),
                (
                    "trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "catalogue_length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "roll_width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_flammable", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "line_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_estimate", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "submitted"),
                    models.Q(("job_number_key", ""), _negated=True),
                ),
                fields=("job_number_key",),
                name="one_active_order_per_job",
            ),
        ),
    ]
