# Generated by Django 5.2.18 on 2026-10-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="roll_width_m",
        ),
    ]
