# Generated by Django 5.2.18 on 2026-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_line_roll_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="kit_name",
            field=models.CharField(
                blank=True,
                help_text="Set when the line was added as part of a kit.",
                max_length=120,
            ),
        ),
    ]
