# Generated by Django 5.2.18 on 2026-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_line_kit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="operative_name",
            field=models.CharField(
                blank=True,
                help_text="Required for occupied properties: who stores are delivering to.",
                max_length=150,
            ),
        ),
    ]
