# Generated by Django 5.2.18 on 2026-10-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_operative_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="anonymised_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="anonymous_id",
        ),
    ]
