# Generated by Django 5.2.18 on 2026-10-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_remove_line_roll_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submitted", "New order"),
                            ("amended", "Amended"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("resolved", "Failed, then sent by a later retry or email"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("recipient", models.CharField(max_length=254)),
                ("subject", models.CharField(max_length=300)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
