# Generated by Django 5.2.18 on 2026-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderemail",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
